version: "3.8"
services:
  docker-mysql:
    container_name: docker-mysql
    hostname: docker-mysql.localhost.com
    image: bhawnesh_dipu/docker-mysql:v0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ../docker-mysql/src/main/resources/mysql-env.env
    volumes:
      - mysql-data:/var/lib/mysql
    build:
      context: ../docker-mysql/src/main/resources/
      dockerfile: Dockerfile
    ports:
      - "13306:13306"
      - "3306:3306"

  docker-spring-web:
    container_name: docker-spring-web
    hostname: docker-spring-web.localhost.com
    image: bhawnesh_dipu/docker-spring-web:v0
    restart: always
    env_file:
      - src/main/resources/spring-web-env.env
    build:
      context: target
      dockerfile: Dockerfile
    ports:
      - "18081:18081"
      - "15005:15005"


volumes:
  mysql-data:

