version: "3.8"
services:
  docker-mysql:
    container_name: docker-mysql
    hostname: docker-mysql.localhost.com
    image: bhawnesh_dipu/docker-mysql:v0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - src/main/resources/mysql-env.env
    volumes:
        - mysql-data:/var/lib/mysql
    build:
      context: ./src/main/resources/
      dockerfile: Dockerfile
    ports:
      - "13306:13306"
      - "3306:3306"
volumes:
  mysql-data: